"""Mission definitions — structured mission data.

Each mission is a dict with objectives. Missions are loaded by
the mission_loader and run by the mission_runner.
"""

from __future__ import annotations

from typing import Any

MISSIONS: dict[str, dict[str, Any]] = {
    "linux-basics": {
        "id": "linux-basics",
        "title": "Linux Basics",
        "description": "Learn essential Linux commands.",
        "difficulty": "Easy",
        "category": "linux",
        "xp_total": 200,
        "estimated_minutes": 15,
        "learn": ["Navigating the filesystem", "Listing & revealing hidden files",
                  "Reading files with cat", "Creating files & directories",
                  "Command history"],
        "objectives": [
            {
                "id": "lb-1",
                "title": "Where am I?",
                "description": "Use the command that shows your current working directory.",
                "hint": "The command is three letters: p, w, d.",
                "validate": {"type": "command", "match": "pwd"},
                "xp": 20,
            },
            {
                "id": "lb-2",
                "title": "List Files",
                "description": "List the contents of the current directory.",
                "hint": "Use 'ls' to list files.",
                "validate": {"type": "command", "match": "ls"},
                "xp": 20,
            },
            {
                "id": "lb-3",
                "title": "Hidden Files",
                "description": "List ALL files including hidden ones (files starting with a dot).",
                "hint": "Add the -la flag to ls.",
                "validate": {"type": "command", "match": "ls -la"},
                "xp": 25,
            },
            {
                "id": "lb-4",
                "title": "Change Directory",
                "description": "Navigate into the Documents folder.",
                "hint": "Use 'cd Documents'.",
                "validate": {"type": "cwd", "match": "/home/student/Documents"},
                "xp": 25,
            },
            {
                "id": "lb-5",
                "title": "Read a File",
                "description": "Read the contents of welcome.txt inside Documents.",
                "hint": "Use 'cat welcome.txt' (make sure you're in Documents).",
                "validate": {"type": "command", "match": "cat welcome.txt"},
                "xp": 25,
            },
            {
                "id": "lb-6",
                "title": "Create a File",
                "description": "Create a new file called notes.txt.",
                "hint": "Use 'touch notes.txt'.",
                "validate": {"type": "file_exists", "match": "/home/student/notes.txt"},
                "xp": 30,
            },
            {
                "id": "lb-7",
                "title": "Create a Folder",
                "description": "Create a new directory called practice.",
                "hint": "Use 'mkdir practice'.",
                "validate": {"type": "dir_exists", "match": "/home/student/practice"},
                "xp": 30,
            },
            {
                "id": "lb-8",
                "title": "View History",
                "description": "View your command history.",
                "hint": "Type 'history'.",
                "validate": {"type": "command", "match": "history"},
                "xp": 25,
            },
        ],
        "filesystem": {
            "home": {"student": {
                "Documents": {
                    "welcome.txt": "Welcome to YushaCyber!\nYou're learning Linux. Keep going!\n",
                    "readme.txt": "Read the welcome file first.\n",
                },
                "Downloads": {},
                "Desktop": {},
                ".bashrc": "# ~/.bashrc\n",
                ".profile": "# ~/.profile\n",
            }},
            "etc": {
                "passwd": "root:x:0:0:root:/root:/bin/bash\nstudent:x:1000:1000::/home/student:/bin/bash\n",
                "hostname": "yushacyber-lab\n",
            },
            "var": {"log": {"syslog": "System log entries here.\n"}},
            "tmp": {},
        },
        "next_mission": "linux-permissions",
    },
    "linux-permissions": {
        "id": "linux-permissions",
        "title": "Linux Permissions",
        "description": "Master file permissions, ownership, and chmod/chown on a realistic Linux-style filesystem.",
        "difficulty": "Beginner",
        "category": "linux",
        "xp_total": 200,
        "estimated_minutes": 20,
        "learn": ["Linux permissions", "Users", "Groups", "chmod",
                  "Ownership", "Permission notation"],
        "objectives": [
            {
                "id": "lp-1",
                "title": "Read Permission Notation",
                "description": "List the contents of ~/permissions in long format to see permission bits, owners, and groups.",
                "hint": "Use 'ls -l' (try it inside the permissions folder: cd permissions).",
                "validate": {"type": "command", "match": "ls -l"},
                "xp": 20,
            },
            {
                "id": "lp-2",
                "title": "Identify Yourself",
                "description": "Find out which user you're currently logged in as.",
                "hint": "The command is 'whoami'.",
                "validate": {"type": "command", "match": "whoami"},
                "xp": 15,
            },
            {
                "id": "lp-3",
                "title": "Inspect Your Identity",
                "description": "Inspect your full user and group ID information.",
                "hint": "Type 'id'.",
                "validate": {"type": "command", "match": "id"},
                "xp": 15,
            },
            {
                "id": "lp-4",
                "title": "Check Your Groups",
                "description": "List the groups you belong to.",
                "hint": "Type 'groups'.",
                "validate": {"type": "command", "match": "groups"},
                "xp": 15,
            },
            {
                "id": "lp-5",
                "title": "Access Denied",
                "description": "Try to read private.txt in ~/permissions and see what happens when you don't have permission.",
                "hint": "Use 'cat private.txt' — it should be denied.",
                "validate": {"type": "output_contains", "match": "permission denied"},
                "xp": 25,
            },
            {
                "id": "lp-6",
                "title": "Grant Read Access",
                "description": "Use chmod to make challenge.txt readable by everyone (mode 644).",
                "hint": "Use 'chmod 644 challenge.txt'.",
                "validate": {"type": "file_mode", "match": "644",
                             "path": "/home/student/permissions/challenge.txt"},
                "xp": 30,
            },
            {
                "id": "lp-7",
                "title": "Verify the Change",
                "description": "Confirm challenge.txt now shows the new permission bits by listing it directly.",
                "hint": "Use 'ls -l challenge.txt' (from ~/permissions) and check it changed to read for everyone.",
                "validate": {"type": "file_mode", "match": "644",
                             "path": "/home/student/permissions/challenge.txt"},
                "xp": 25,
            },
            {
                "id": "lp-8",
                "title": "Take Ownership",
                "description": "Take ownership of private.txt so you can finally read it.",
                "hint": "Use 'chown student private.txt'.",
                "validate": {"type": "file_owner", "match": "student",
                             "path": "/home/student/permissions/private.txt"},
                "xp": 55,
            },
        ],
        "filesystem": {
            "home": {"student": {
                "permissions": {
                    "public.txt": "Anyone can read this file. Permissions are your first line of defense.\n",
                    "private.txt": "Only the owner should be able to read this. If you can see this, ownership matters.\n",
                    "challenge.txt": "Locked down until you grant yourself read access.\n",
                },
                "Documents": {},
                "Downloads": {},
                "Desktop": {},
                ".bashrc": "# ~/.bashrc\n",
                ".profile": "# ~/.profile\n",
            }},
            "etc": {
                "passwd": "root:x:0:0:root:/root:/bin/bash\nstudent:x:1000:1000::/home/student:/bin/bash\n",
                "hostname": "yushacyber-lab\n",
            },
            "var": {"log": {"syslog": "System log entries here.\n"}},
            "tmp": {},
        },
        "permissions": {
            "/home/student/permissions/public.txt": {"mode": "644", "owner": "student", "group": "student"},
            "/home/student/permissions/private.txt": {"mode": "600", "owner": "root", "group": "root"},
            "/home/student/permissions/challenge.txt": {"mode": "000", "owner": "student", "group": "student"},
        },
        "next_mission": "bash-fundamentals",
    },
    "bash-fundamentals": {
        "id": "bash-fundamentals",
        "title": "Bash Fundamentals",
        "description": "Learn Bash scripting fundamentals — variables, environment variables, "
                       "command substitution, pipes, redirection, scripts, conditionals, and loops.",
        "difficulty": "Beginner",
        "category": "linux",
        "xp_total": 250,
        "estimated_minutes": 28,
        "learn": ["Variables", "echo", "Command substitution", "Environment variables",
                  "Pipes", "Redirection", "Simple shell scripts", "Executable permissions",
                  "Basic if statements", "Basic loops"],
        "objectives": [
            {
                "id": "bf-1",
                "title": "Navigate to Your Workspace",
                "description": "Move into your bash-lab workspace.",
                "hint": "Use 'cd bash-lab'.",
                "validate": {"type": "cwd", "match": "/home/student/bash-lab"},
                "xp": 10,
            },
            {
                "id": "bf-2",
                "title": "Create a Variable",
                "description": "Create a shell variable called name holding your identity.",
                "hint": 'Use name="student" — no spaces around the =.',
                "validate": {"type": "command", "match": "name="},
                "xp": 15,
            },
            {
                "id": "bf-3",
                "title": "Print the Variable",
                "description": "Print the value of the variable you just created.",
                "hint": 'Use echo "$name".',
                "validate": {"type": "output_contains", "match": "student"},
                "xp": 15,
            },
            {
                "id": "bf-4",
                "title": "Create an Environment Variable",
                "description": "Export an environment variable called LAB so child processes can see it.",
                "hint": 'Use export LAB="yushacyber".',
                "validate": {"type": "command", "match": "export lab"},
                "xp": 15,
            },
            {
                "id": "bf-5",
                "title": "Inspect the Environment Variable",
                "description": "Print the LAB environment variable.",
                "hint": 'Use echo "$LAB".',
                "validate": {"type": "output_contains", "match": "yushacyber"},
                "xp": 15,
            },
            {
                "id": "bf-6",
                "title": "Command Substitution",
                "description": "Store the output of another command inside a variable.",
                "hint": "Use current=$(pwd).",
                "validate": {"type": "command", "match": "$(pwd)"},
                "xp": 20,
            },
            {
                "id": "bf-7",
                "title": "Use a Pipe",
                "description": "Filter the workspace file listing so only .txt files show.",
                "hint": "Use ls | grep txt.",
                "validate": {"type": "output_contains", "match": "files.txt"},
                "xp": 20,
            },
            {
                "id": "bf-8",
                "title": "Redirect Output",
                "description": "Redirect the file listing into a new file called output.txt.",
                "hint": "Use ls > output.txt.",
                "validate": {"type": "file_exists", "match": "/home/student/bash-lab/output.txt"},
                "xp": 20,
            },
            {
                "id": "bf-9",
                "title": "Create a Bash Script",
                "description": "Write a one-line script.sh that prints a greeting.",
                "hint": 'Use echo \'echo "Hello from YushaCyber!"\' > script.sh.',
                "validate": {"type": "file_contains", "match": "Hello from YushaCyber",
                             "path": "/home/student/bash-lab/script.sh"},
                "xp": 20,
            },
            {
                "id": "bf-10",
                "title": "Make It Executable",
                "description": "Give script.sh executable permission.",
                "hint": "Use chmod +x script.sh.",
                "validate": {"type": "file_mode", "match": "755",
                             "path": "/home/student/bash-lab/script.sh"},
                "xp": 20,
            },
            {
                "id": "bf-11",
                "title": "Execute the Script",
                "description": "Run your script and see it print the greeting.",
                "hint": "Use ./script.sh.",
                "validate": {"type": "output_contains", "match": "Hello from YushaCyber"},
                "xp": 25,
            },
            {
                "id": "bf-12",
                "title": "Write a Conditional",
                "description": "Use an if statement to check that script.sh exists.",
                "hint": 'Use if [ -f script.sh ]; then echo "found"; fi.',
                "validate": {"type": "output_contains", "match": "found"},
                "xp": 30,
            },
            {
                "id": "bf-13",
                "title": "Write a Loop",
                "description": "Use a for loop to count from 1 to 3.",
                "hint": 'Use for i in 1 2 3; do echo "count-$i"; done.',
                "validate": {"type": "output_contains", "match": "count-3"},
                "xp": 25,
            },
        ],
        "filesystem": {
            "home": {"student": {
                "bash-lab": {
                    "files.txt": "sample data file\n",
                    "notes.md": "not a text export\n",
                },
                "Documents": {},
                "Downloads": {},
                "Desktop": {},
                ".bashrc": "# ~/.bashrc\n",
                ".profile": "# ~/.profile\n",
            }},
            "etc": {
                "passwd": "root:x:0:0:root:/root:/bin/bash\nstudent:x:1000:1000::/home/student:/bin/bash\n",
                "hostname": "yushacyber-lab\n",
            },
            "var": {"log": {"syslog": "System log entries here.\n"}},
            "tmp": {},
        },
        "next_mission": "networking-fundamentals",
    },
    "networking-fundamentals": {
        "id": "networking-fundamentals",
        "title": "Networking Fundamentals",
        "description": "Explore IP addressing, routing, DNS, and listening services on a "
                       "simulated Linux networking lab.",
        "difficulty": "Beginner",
        "category": "networking",
        "xp_total": 300,
        "estimated_minutes": 35,
        "learn": ["IP addresses", "IPv4", "Network interfaces", "Subnet masks",
                  "Default gateway", "DNS", "Ports", "TCP vs UDP",
                  "Basic connectivity", "Routing"],
        "objectives": [
            {
                "id": "net-1",
                "title": "Inspect Network Interfaces",
                "description": "List your machine's network interfaces and their addresses.",
                "hint": "Use 'ip addr'.",
                "validate": {"type": "command", "match": "ip addr"},
                "xp": 20,
            },
            {
                "id": "net-2",
                "title": "Identify Your IPv4 Address",
                "description": "Find your own IPv4 address in the interface list.",
                "hint": "Look for the 'inet' line under eth0.",
                "validate": {"type": "output_contains", "match": "10.10.10.20"},
                "xp": 20,
            },
            {
                "id": "net-3",
                "title": "Inspect the Routing Table",
                "description": "List the routes your machine knows about.",
                "hint": "Use 'ip route'.",
                "validate": {"type": "command", "match": "ip route"},
                "xp": 20,
            },
            {
                "id": "net-4",
                "title": "Identify the Default Gateway",
                "description": "Find the default gateway in the routing table.",
                "hint": "Look for the 'default via' line.",
                "validate": {"type": "output_contains", "match": "default via 10.10.10.1"},
                "xp": 20,
            },
            {
                "id": "net-5",
                "title": "Test Connectivity to the Gateway",
                "description": "Ping the default gateway to confirm you can reach it.",
                "hint": "Use 'ping 10.10.10.1'.",
                "validate": {"type": "output_contains", "match": "64 bytes from 10.10.10.1:"},
                "xp": 25,
            },
            {
                "id": "net-6",
                "title": "Test Connectivity to the Web Server",
                "description": "Ping the web server to confirm the lab network is reachable.",
                "hint": "Use 'ping 10.10.10.10'.",
                "validate": {"type": "output_contains", "match": "64 bytes from 10.10.10.10:"},
                "xp": 25,
            },
            {
                "id": "net-7",
                "title": "Inspect Listening Services",
                "description": "List the services listening on your own machine.",
                "hint": "Use 'ss'.",
                "validate": {"type": "command", "match": "ss"},
                "xp": 25,
            },
            {
                "id": "net-8",
                "title": "Identify an Open TCP Port",
                "description": "Find the open web server port (80) in the listening services.",
                "hint": "Look for the ':80' entry in the ss output.",
                "validate": {"type": "output_contains", "match": "10.10.10.20:80"},
                "xp": 30,
            },
            {
                "id": "net-9",
                "title": "Perform a DNS Lookup",
                "description": "Resolve example.local using the simulated DNS server.",
                "hint": "Use 'nslookup example.local'.",
                "validate": {"type": "output_contains", "match": "Address: 10.10.10.10"},
                "xp": 30,
            },
            {
                "id": "net-10",
                "title": "Inspect the Hosts File",
                "description": "Check the local hosts file for static name mappings.",
                "hint": "Use 'cat /etc/hosts'.",
                "validate": {"type": "output_contains", "match": "student-pc"},
                "xp": 25,
            },
            {
                "id": "net-11",
                "title": "Identify the DNS Server",
                "description": "Find the IP address of the simulated DNS server.",
                "hint": "Check the 'Server:' line from your nslookup output.",
                "validate": {"type": "output_contains", "match": "10.10.10.53"},
                "xp": 25,
            },
            {
                "id": "net-12",
                "title": "Final Networking Challenge",
                "description": "Confirm connectivity to the file server to complete the lab.",
                "hint": "Use 'ping 10.10.10.30'.",
                "validate": {"type": "output_contains", "match": "64 bytes from 10.10.10.30:"},
                "xp": 35,
            },
        ],
        "filesystem": {
            "home": {"student": {
                "Documents": {},
                "Downloads": {},
                "Desktop": {},
                ".bashrc": "# ~/.bashrc\n",
                ".profile": "# ~/.profile\n",
            }},
            "etc": {
                "passwd": "root:x:0:0:root:/root:/bin/bash\nstudent:x:1000:1000::/home/student:/bin/bash\n",
                "hostname": "yushacyber-lab\n",
                "hosts": "127.0.0.1 localhost\n"
                        "10.10.10.20 student-pc\n"
                        "10.10.10.1 gateway\n"
                        "10.10.10.10 example.local web01\n"
                        "10.10.10.53 dns01\n"
                        "10.10.10.30 fileserver.local fileserver\n",
            },
            "var": {"log": {"syslog": "System log entries here.\n"}},
            "tmp": {},
        },
        "network": {
            "student_ip": "10.10.10.20",
            "dns_server_ip": "10.10.10.53",
            "hosts": {
                "10.10.10.20": {
                    "hostname": "student-pc",
                    "interfaces": [
                        {"name": "eth0", "ip": "10.10.10.20", "cidr": 24, "state": "UP"},
                        {"name": "lo", "ip": "127.0.0.1", "cidr": 8, "state": "UP"},
                    ],
                    "routes": [
                        {"destination": "default", "via": "10.10.10.1",
                         "dev": "eth0", "is_default": True},
                        {"destination": "10.10.10.0/24", "dev": "eth0"},
                    ],
                    "services": [
                        {"port": 22, "proto": "tcp", "name": "ssh"},
                        {"port": 80, "proto": "tcp", "name": "http"},
                    ],
                },
                "10.10.10.1": {"hostname": "gateway", "reachable": True},
                "10.10.10.10": {"hostname": "web01", "reachable": True,
                                "services": [{"port": 80, "proto": "tcp", "name": "http"}]},
                "10.10.10.53": {"hostname": "dns01", "reachable": True,
                                "services": [{"port": 53, "proto": "udp", "name": "dns"}]},
                "10.10.10.30": {"hostname": "fileserver", "reachable": True,
                                "services": [{"port": 445, "proto": "tcp", "name": "smb"}]},
            },
            "dns_records": [
                {"hostname": "example.local", "ip": "10.10.10.10"},
                {"hostname": "fileserver.local", "ip": "10.10.10.30"},
            ],
        },
        "next_mission": "network-troubleshooting",
    },
    "network-troubleshooting": {
        "id": "network-troubleshooting",
        "title": "Network Troubleshooting",
        "description": "Diagnose and repair a broken simulated network by reasoning from "
                       "symptoms — interface, IP, gateway, DNS, and services — one layer "
                       "at a time.",
        "difficulty": "Beginner → Intermediate",
        "category": "networking",
        "xp_total": 350,
        "estimated_minutes": 40,
        "learn": ["Systematic troubleshooting", "Interface state", "IP/subnet mismatches",
                  "Default gateway misconfiguration", "DNS vs. connectivity failures",
                  "Service availability", "Simulated network repair"],
        "objectives": [
            {
                "id": "nt-1",
                "title": "Identify the Problem",
                "description": "Your network connection is broken. Try to reach the gateway and see what happens.",
                "hint": "Use 'ping 10.10.10.1'.",
                "validate": {"type": "output_contains", "match": "Network is unreachable"},
                "xp": 20,
            },
            {
                "id": "nt-2",
                "title": "Inspect the Interface",
                "description": "Check the state of your network interfaces.",
                "hint": "Use 'ip link'.",
                "validate": {"type": "command", "match": "ip link"},
                "xp": 15,
            },
            {
                "id": "nt-3",
                "title": "Identify the Interface Is Down",
                "description": "Confirm eth0 is reporting a DOWN state.",
                "hint": "Look at the 'state' field in the ip link output.",
                "validate": {"type": "output_contains", "match": "state DOWN"},
                "xp": 20,
            },
            {
                "id": "nt-4",
                "title": "Bring the Interface Up",
                "description": "Enable eth0 so the machine can use the network again.",
                "hint": "Use 'ip link set eth0 up'.",
                "validate": {"type": "network_state", "check": "interface_state",
                             "interface": "eth0", "match": "UP"},
                "xp": 30,
            },
            {
                "id": "nt-5",
                "title": "Inspect IP Configuration",
                "description": "Check the IP address currently assigned to eth0.",
                "hint": "Use 'ip addr'.",
                "validate": {"type": "command", "match": "ip addr"},
                "xp": 15,
            },
            {
                "id": "nt-6",
                "title": "Identify the IP Mismatch",
                "description": "The assigned address is on the wrong subnet for this network (10.10.10.0/24).",
                "hint": "Compare the address in 'ip addr' against the lab network range.",
                "validate": {"type": "output_contains", "match": "10.10.20.50"},
                "xp": 20,
            },
            {
                "id": "nt-7",
                "title": "Fix the IP Configuration",
                "description": "Assign the correct address for this network to eth0.",
                "hint": "Use 'ip addr add 10.10.10.20/24 dev eth0'.",
                "validate": {"type": "network_state", "check": "interface_ip",
                             "interface": "eth0", "match": "10.10.10.20"},
                "xp": 30,
            },
            {
                "id": "nt-8",
                "title": "Inspect Routing Configuration",
                "description": "Check the routing table for a default route.",
                "hint": "Use 'ip route'.",
                "validate": {"type": "command", "match": "ip route"},
                "xp": 15,
            },
            {
                "id": "nt-9",
                "title": "Identify the Wrong Gateway",
                "description": "The default route points to a gateway outside this network's range.",
                "hint": "Compare the 'via' address against 10.10.10.0/24.",
                "validate": {"type": "output_contains", "match": "10.10.20.1"},
                "xp": 20,
            },
            {
                "id": "nt-10",
                "title": "Fix the Default Gateway",
                "description": "Point the default route at the correct gateway.",
                "hint": "Use 'ip route add default via 10.10.10.1'.",
                "validate": {"type": "network_state", "check": "default_gateway",
                             "match": "10.10.10.1"},
                "xp": 30,
            },
            {
                "id": "nt-11",
                "title": "Verify Gateway Connectivity",
                "description": "Confirm you can now reach the gateway.",
                "hint": "Use 'ping 10.10.10.1'.",
                "validate": {"type": "output_contains", "match": "64 bytes from 10.10.10.1:"},
                "xp": 25,
            },
            {
                "id": "nt-12",
                "title": "Verify Remote Connectivity",
                "description": "Confirm you can now reach a host beyond the gateway.",
                "hint": "Use 'ping 10.10.10.10'.",
                "validate": {"type": "output_contains", "match": "64 bytes from 10.10.10.10:"},
                "xp": 30,
            },
            {
                "id": "nt-13",
                "title": "Diagnose the DNS Issue",
                "description": "Connectivity is restored, but name resolution still fails. "
                               "Confirm this is a DNS problem, not a network problem.",
                "hint": "Use 'nslookup example.local' — it fails even though ping works.",
                "validate": {"type": "output_contains", "match": "NXDOMAIN"},
                "xp": 35,
            },
            {
                "id": "nt-14",
                "title": "Complete the Network Audit",
                "description": "Finish up by confirming which services are running on your machine.",
                "hint": "Use 'ss'.",
                "validate": {"type": "command", "match": "ss"},
                "xp": 45,
            },
        ],
        "filesystem": {
            "home": {"student": {
                "Documents": {},
                "Downloads": {},
                "Desktop": {},
                ".bashrc": "# ~/.bashrc\n",
                ".profile": "# ~/.profile\n",
            }},
            "etc": {
                "passwd": "root:x:0:0:root:/root:/bin/bash\nstudent:x:1000:1000::/home/student:/bin/bash\n",
                "hostname": "yushacyber-lab\n",
                "hosts": "127.0.0.1 localhost\n"
                        "10.10.10.20 student-pc\n"
                        "10.10.10.1 gateway\n"
                        "10.10.10.10 example.local web01\n"
                        "10.10.10.53 dns01\n",
            },
            "var": {"log": {"syslog": "System log entries here.\n"}},
            "tmp": {},
        },
        "network": {
            "student_ip": "10.10.10.20",
            "dns_server_ip": "10.10.10.53",
            "dns_working": False,
            "hosts": {
                "10.10.10.20": {
                    "hostname": "student-pc",
                    "interfaces": [
                        {"name": "eth0", "ip": "10.10.20.50", "cidr": 24, "state": "DOWN"},
                        {"name": "lo", "ip": "127.0.0.1", "cidr": 8, "state": "UP"},
                    ],
                    "routes": [
                        {"destination": "default", "via": "10.10.20.1",
                         "dev": "eth0", "is_default": True},
                        {"destination": "10.10.10.0/24", "dev": "eth0"},
                    ],
                    "services": [
                        {"port": 22, "proto": "tcp", "name": "ssh"},
                        {"port": 80, "proto": "tcp", "name": "http"},
                    ],
                },
                "10.10.10.1": {"hostname": "gateway", "reachable": True},
                "10.10.10.10": {"hostname": "web01", "reachable": True,
                                "services": [{"port": 80, "proto": "tcp", "name": "http"}]},
                "10.10.10.53": {"hostname": "dns01", "reachable": True,
                                "services": [{"port": 53, "proto": "udp", "name": "dns"}]},
            },
            "dns_records": [
                {"hostname": "example.local", "ip": "10.10.10.10"},
            ],
        },
        "next_mission": None,
    },
}


def get_mission(mission_id: str) -> dict[str, Any] | None:
    return MISSIONS.get(mission_id)


def list_missions() -> list[dict[str, Any]]:
    return [{"id": m["id"], "title": m["title"],
             "difficulty": m["difficulty"], "xp_total": m["xp_total"],
             "objectives": len(m["objectives"])}
            for m in MISSIONS.values()]
