"""roadmap learning models: categories, modules, lessons, user progress

Revision ID: 13306b024792
Revises: fc97c79d3658
Create Date: 2026-07-07 04:45:43.191347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13306b024792'
down_revision = 'fc97c79d3658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_categories',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_categories_display_order'), ['display_order'], unique=False)

    op.create_table('roadmap_modules',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['roadmap_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_modules_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_modules_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_modules_slug'), ['slug'], unique=True)

    op.create_table('lessons',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('content_path', sa.String(length=255), nullable=True),
    sa.Column('lesson_type', sa.String(length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['roadmap_modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'slug', name='uq_lesson_module_slug')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_module_id'), ['module_id'], unique=False)

    op.create_table('user_lesson_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_progress_user_lesson')
    )
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lesson_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lesson_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_lesson_progress_lesson_id'))

    op.drop_table('user_lesson_progress')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_module_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_display_order'))

    op.drop_table('lessons')
    with op.batch_alter_table('roadmap_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_modules_slug'))
        batch_op.drop_index(batch_op.f('ix_roadmap_modules_display_order'))
        batch_op.drop_index(batch_op.f('ix_roadmap_modules_category_id'))

    op.drop_table('roadmap_modules')
    with op.batch_alter_table('roadmap_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_categories_display_order'))

    op.drop_table('roadmap_categories')
    # ### end Alembic commands ###
