"""lab prerequisite for sequential unlock

Revision ID: 6b926ef3bc15
Revises: ab12478a844d
Create Date: 2026-07-14 04:34:39.433480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b926ef3bc15'
down_revision = 'ab12478a844d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite_lab_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_labs_prerequisite_lab_id'), ['prerequisite_lab_id'], unique=False)
        batch_op.create_foreign_key('fk_labs_prerequisite_lab_id', 'labs', ['prerequisite_lab_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_labs_prerequisite_lab_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_labs_prerequisite_lab_id'))
        batch_op.drop_column('prerequisite_lab_id')

    # ### end Alembic commands ###
