"""resources hub models

Revision ID: 890173ec4508
Revises: 89a81c0b626c
Create Date: 2026-07-13 08:19:01.920827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890173ec4508'
down_revision = '89a81c0b626c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_categories_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_categories_slug'), ['slug'], unique=True)

    op.create_table('resources',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('estimated_read_minutes', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['resource_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_slug'))
        batch_op.drop_index(batch_op.f('ix_resources_is_featured'))
        batch_op.drop_index(batch_op.f('ix_resources_display_order'))
        batch_op.drop_index(batch_op.f('ix_resources_category_id'))

    op.drop_table('resources')
    with op.batch_alter_table('resource_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_resource_categories_display_order'))

    op.drop_table('resource_categories')
    # ### end Alembic commands ###
