"""cyber labs models

Revision ID: 89a81c0b626c
Revises: b69c06963e3c
Create Date: 2026-07-13 04:14:32.441530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a81c0b626c'
down_revision = 'b69c06963e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_categories_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_categories_slug'), ['slug'], unique=True)

    op.create_table('labs',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lab_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labs_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labs_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_labs_slug'), ['slug'], unique=True)

    op.create_table('lab_files',
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('filepath', sa.String(length=400), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_files_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_files_lab_id'), ['lab_id'], unique=False)

    op.create_table('lab_objectives',
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_objectives_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_objectives_lab_id'), ['lab_id'], unique=False)

    op.create_table('user_lab_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lab_id', name='uq_user_lab_progress')
    )
    with op.batch_alter_table('user_lab_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_lab_progress_lab_id'), ['lab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lab_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lab_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lab_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_lab_progress_lab_id'))

    op.drop_table('user_lab_progress')
    with op.batch_alter_table('lab_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_objectives_lab_id'))
        batch_op.drop_index(batch_op.f('ix_lab_objectives_display_order'))

    op.drop_table('lab_objectives')
    with op.batch_alter_table('lab_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_files_lab_id'))
        batch_op.drop_index(batch_op.f('ix_lab_files_display_order'))

    op.drop_table('lab_files')
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labs_slug'))
        batch_op.drop_index(batch_op.f('ix_labs_display_order'))
        batch_op.drop_index(batch_op.f('ix_labs_category_id'))

    op.drop_table('labs')
    with op.batch_alter_table('lab_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_lab_categories_display_order'))

    op.drop_table('lab_categories')
    # ### end Alembic commands ###
