"""certificate models

Revision ID: a75bd363cfb9
Revises: 80cb97a1c939
Create Date: 2026-07-11 11:37:53.361242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75bd363cfb9'
down_revision = '80cb97a1c939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('certificate_type', sa.String(length=50), nullable=False),
    sa.Column('required_modules', sa.Text(), nullable=True),
    sa.Column('required_quizzes', sa.Text(), nullable=True),
    sa.Column('required_xp', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_slug'), ['slug'], unique=True)

    op.create_table('user_certificates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('certificate_code', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'certificate_id', name='uq_user_certificate')
    )
    with op.batch_alter_table('user_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_certificates_certificate_code'), ['certificate_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_certificates_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_certificates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_certificates_certificate_id'))
        batch_op.drop_index(batch_op.f('ix_user_certificates_certificate_code'))

    op.drop_table('user_certificates')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_slug'))
        batch_op.drop_index(batch_op.f('ix_certificates_display_order'))

    op.drop_table('certificates')
    # ### end Alembic commands ###
