"""lab engine: simulators, filesystem, sessions, objective progress

Revision ID: ab12478a844d
Revises: 890173ec4508
Create Date: 2026-07-13 14:51:39.309531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab12478a844d'
down_revision = '890173ec4508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulator_engines',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulator_engines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulator_engines_key'), ['key'], unique=True)

    op.create_table('lab_filesystem_nodes',
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('node_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('permissions', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'path', name='uq_lab_fs_path')
    )
    with op.batch_alter_table('lab_filesystem_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_filesystem_nodes_lab_id'), ['lab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_filesystem_nodes_path'), ['path'], unique=False)

    op.create_table('user_lab_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lab_id', name='uq_user_lab_session')
    )
    with op.batch_alter_table('user_lab_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_lab_sessions_lab_id'), ['lab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lab_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_objective_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['lab_objectives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'objective_id', name='uq_user_objective')
    )
    with op.batch_alter_table('user_objective_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_objective_progress_objective_id'), ['objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_objective_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('lab_objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('validator_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('validator_data_json', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('hint1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hint2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hint3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('xp_reward', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_optional', sa.Boolean(), nullable=False))

    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simulator_key', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_interactive', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_labs_simulator_key'), ['simulator_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labs_simulator_key'))
        batch_op.drop_column('is_interactive')
        batch_op.drop_column('simulator_key')

    with op.batch_alter_table('lab_objectives', schema=None) as batch_op:
        batch_op.drop_column('is_optional')
        batch_op.drop_column('xp_reward')
        batch_op.drop_column('hint3')
        batch_op.drop_column('hint2')
        batch_op.drop_column('hint1')
        batch_op.drop_column('validator_data_json')
        batch_op.drop_column('validator_type')
        batch_op.drop_column('instruction')

    with op.batch_alter_table('user_objective_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_objective_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_objective_progress_objective_id'))

    op.drop_table('user_objective_progress')
    with op.batch_alter_table('user_lab_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lab_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_lab_sessions_lab_id'))

    op.drop_table('user_lab_sessions')
    with op.batch_alter_table('lab_filesystem_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_filesystem_nodes_path'))
        batch_op.drop_index(batch_op.f('ix_lab_filesystem_nodes_lab_id'))

    op.drop_table('lab_filesystem_nodes')
    with op.batch_alter_table('simulator_engines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulator_engines_key'))

    op.drop_table('simulator_engines')
    # ### end Alembic commands ###
