"""challenge hints

Revision ID: b69c06963e3c
Revises: 8facd1d87242
Create Date: 2026-07-12 14:41:40.208022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69c06963e3c'
down_revision = '8facd1d87242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_hints',
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge_hints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_hints_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_hints_display_order'), ['display_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_hints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_hints_display_order'))
        batch_op.drop_index(batch_op.f('ix_challenge_hints_challenge_id'))

    op.drop_table('challenge_hints')
    # ### end Alembic commands ###
