"""quiz model revisions: question_text, time limits, attempt percentage

Revision ID: c4acb9817697
Revises: eca37a8c6376
Create Date: 2026-07-10 08:12:42.451137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4acb9817697'
down_revision = 'eca37a8c6376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_text', sa.Text(), nullable=False, server_default=''))
        batch_op.drop_column('question')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('time_taken_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_attempts', schema=None) as batch_op:
        batch_op.drop_column('time_taken_seconds')
        batch_op.drop_column('percentage')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('time_limit_minutes')

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.TEXT(), nullable=False))
        batch_op.drop_column('question_text')

    # ### end Alembic commands ###
