"""user module progress: per-user module progression

Revision ID: d810f850007c
Revises: 13306b024792
Create Date: 2026-07-10 06:37:35.096612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd810f850007c'
down_revision = '13306b024792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_module_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('bonus_awarded', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['roadmap_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_module_progress_user_module')
    )
    with op.batch_alter_table('user_module_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_module_progress_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_module_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_module_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_module_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_module_progress_module_id'))

    op.drop_table('user_module_progress')
    # ### end Alembic commands ###
